-- FCI-Rassen Seed — alle wichtigen Rassen auf Deutsch
-- Ausführen: psql -U whelply -d whelply -f prisma/seed-breeds.sql
-- ON CONFLICT: überspringt bereits vorhandene Rassen (nach slug)

-- Erst bestehende Rassen behalten, neue hinzufügen
INSERT INTO breeds (fci_number, name_de, name_en, fci_group, fci_section, slug) VALUES
-- ═══ GRUPPE 1: Hütehunde und Treibhunde ═══
(166, 'Border Collie', 'Border Collie', 1, 1, 'border-collie'),
(251, 'Australian Shepherd', 'Australian Shepherd', 1, 1, 'australian-shepherd'),
(1, 'Deutscher Schäferhund', 'German Shepherd Dog', 1, 1, 'deutscher-schaeferhund'),
(271, 'Berger Blanc Suisse', 'White Swiss Shepherd Dog', 1, 1, 'berger-blanc-suisse'),
(15, 'Briard', 'Briard', 1, 1, 'briard'),
(16, 'Beauceron', 'Beauceron', 1, 1, 'beauceron'),
(5, 'Malinois', 'Belgian Shepherd Malinois', 1, 1, 'malinois'),
(3, 'Groenendael', 'Belgian Shepherd Groenendael', 1, 1, 'groenendael'),
(6, 'Tervueren', 'Belgian Shepherd Tervueren', 1, 1, 'tervueren'),
(4, 'Laekenois', 'Belgian Shepherd Laekenois', 1, 1, 'laekenois'),
(156, 'Collie Langhaar', 'Rough Collie', 1, 1, 'collie-langhaar'),
(296, 'Collie Kurzhaar', 'Smooth Collie', 1, 1, 'collie-kurzhaar'),
(159, 'Shetland Sheepdog', 'Shetland Sheepdog', 1, 1, 'shetland-sheepdog'),
(297, 'Bobtail', 'Old English Sheepdog', 1, 1, 'bobtail'),
(57, 'Bearded Collie', 'Bearded Collie', 1, 1, 'bearded-collie'),
(39, 'Welsh Corgi Pembroke', 'Welsh Corgi Pembroke', 1, 1, 'welsh-corgi-pembroke'),
(38, 'Welsh Corgi Cardigan', 'Welsh Corgi Cardigan', 1, 1, 'welsh-corgi-cardigan'),
(11, 'Berger de Picardie', 'Berger de Picardie', 1, 1, 'berger-de-picardie'),
(86, 'Komondor', 'Komondor', 1, 1, 'komondor'),
(87, 'Kuvasz', 'Kuvasz', 1, 1, 'kuvasz'),
(88, 'Mudi', 'Mudi', 1, 1, 'mudi'),
(90, 'Puli', 'Puli', 1, 1, 'puli'),
(91, 'Pumi', 'Pumi', 1, 1, 'pumi'),
(287, 'Australian Cattle Dog', 'Australian Cattle Dog', 1, 2, 'australian-cattle-dog'),
(14, 'Bouvier des Flandres', 'Bouvier des Flandres', 1, 2, 'bouvier-des-flandres'),
(2, 'Australian Kelpie', 'Australian Kelpie', 1, 1, 'australian-kelpie'),

-- ═══ GRUPPE 2: Pinscher, Schnauzer, Molosser, Schweizer Sennenhunde ═══
(143, 'Dobermann', 'Dobermann', 2, 1, 'dobermann'),
(184, 'Deutscher Pinscher', 'German Pinscher', 2, 1, 'deutscher-pinscher'),
(185, 'Zwergpinscher', 'Miniature Pinscher', 2, 1, 'zwergpinscher'),
(186, 'Affenpinscher', 'Affenpinscher', 2, 1, 'affenpinscher'),
(181, 'Riesenschnauzer', 'Giant Schnauzer', 2, 1, 'riesenschnauzer'),
(182, 'Schnauzer', 'Standard Schnauzer', 2, 1, 'schnauzer'),
(183, 'Zwergschnauzer', 'Miniature Schnauzer', 2, 1, 'zwergschnauzer'),
(235, 'Deutsche Dogge', 'Great Dane', 2, 2, 'deutsche-dogge'),
(144, 'Rottweiler', 'Rottweiler', 2, 2, 'rottweiler'),
(292, 'Boxer', 'German Boxer', 2, 2, 'boxer'),
(190, 'Bullmastiff', 'Bullmastiff', 2, 2, 'bullmastiff'),
(264, 'Mastiff', 'English Mastiff', 2, 2, 'mastiff'),
(116, 'Cane Corso', 'Cane Corso', 2, 2, 'cane-corso'),
(110, 'Mastino Napoletano', 'Neapolitan Mastiff', 2, 2, 'mastino-napoletano'),
(58, 'Leonberger', 'Leonberger', 2, 2, 'leonberger'),
(145, 'Hovawart', 'Hovawart', 2, 2, 'hovawart'),
(50, 'Neufundländer', 'Newfoundland', 2, 2, 'neufundlaender'),
(226, 'Landseer', 'Landseer', 2, 2, 'landseer'),
(61, 'Bernhardiner', 'St. Bernard', 2, 2, 'bernhardiner'),
(64, 'Bordeauxdogge', 'Dogue de Bordeaux', 2, 2, 'bordeauxdogge'),
(149, 'Bulldog', 'English Bulldog', 2, 2, 'bulldog'),
(309, 'Shar Pei', 'Shar Pei', 2, 2, 'shar-pei'),
(174, 'Russischer Schwarzer Terrier', 'Black Russian Terrier', 2, 1, 'russischer-schwarzer-terrier'),
(45, 'Berner Sennenhund', 'Bernese Mountain Dog', 2, 3, 'berner-sennenhund'),
(58, 'Grosser Schweizer Sennenhund', 'Greater Swiss Mountain Dog', 2, 3, 'grosser-schweizer-sennenhund'),
(46, 'Appenzeller Sennenhund', 'Appenzeller Mountain Dog', 2, 3, 'appenzeller-sennenhund'),
(47, 'Entlebucher Sennenhund', 'Entlebucher Mountain Dog', 2, 3, 'entlebucher-sennenhund'),

-- ═══ GRUPPE 3: Terrier ═══
(7, 'Airedale Terrier', 'Airedale Terrier', 3, 1, 'airedale-terrier'),
(10, 'Border Terrier', 'Border Terrier', 3, 1, 'border-terrier'),
(12, 'Cairn Terrier', 'Cairn Terrier', 3, 2, 'cairn-terrier'),
(78, 'Irish Terrier', 'Irish Terrier', 3, 1, 'irish-terrier'),
(345, 'Jack Russell Terrier', 'Jack Russell Terrier', 3, 2, 'jack-russell-terrier'),
(339, 'Parson Russell Terrier', 'Parson Russell Terrier', 3, 1, 'parson-russell-terrier'),
(169, 'Kerry Blue Terrier', 'Kerry Blue Terrier', 3, 1, 'kerry-blue-terrier'),
(71, 'Staffordshire Bullterrier', 'Staffordshire Bull Terrier', 3, 3, 'staffordshire-bullterrier'),
(11, 'Bull Terrier', 'Bull Terrier', 3, 3, 'bull-terrier'),
(359, 'Miniatur Bull Terrier', 'Miniature Bull Terrier', 3, 3, 'miniatur-bull-terrier'),
(72, 'West Highland White Terrier', 'West Highland White Terrier', 3, 2, 'west-highland-white-terrier'),
(73, 'Scottish Terrier', 'Scottish Terrier', 3, 2, 'scottish-terrier'),
(168, 'Yorkshire Terrier', 'Yorkshire Terrier', 3, 4, 'yorkshire-terrier'),
(85, 'Norwich Terrier', 'Norwich Terrier', 3, 2, 'norwich-terrier'),
(272, 'Norfolk Terrier', 'Norfolk Terrier', 3, 2, 'norfolk-terrier'),
(9, 'Bedlington Terrier', 'Bedlington Terrier', 3, 1, 'bedlington-terrier'),
(169, 'Lakeland Terrier', 'Lakeland Terrier', 3, 1, 'lakeland-terrier'),
(103, 'Fox Terrier Drahthaar', 'Wire Fox Terrier', 3, 1, 'fox-terrier-drahthaar'),
(12, 'Fox Terrier Glatthaar', 'Smooth Fox Terrier', 3, 1, 'fox-terrier-glatthaar'),

-- ═══ GRUPPE 4: Dachshunde ═══
(148, 'Dachshund Kurzhaar', 'Smooth Dachshund', 4, 1, 'dachshund-kurzhaar'),
(148, 'Dachshund Rauhaar', 'Wire-haired Dachshund', 4, 1, 'dachshund-rauhaar'),
(148, 'Dachshund Langhaar', 'Long-haired Dachshund', 4, 1, 'dachshund-langhaar'),

-- ═══ GRUPPE 5: Spitze und Hunde vom Urtyp ═══
(97, 'Deutscher Spitz', 'German Spitz', 5, 4, 'deutscher-spitz'),
(97, 'Zwergspitz / Pomeranian', 'Pomeranian', 5, 4, 'pomeranian'),
(97, 'Wolfsspitz / Keeshond', 'Keeshond', 5, 4, 'wolfsspitz'),
(97, 'Grossspitz', 'Giant Spitz', 5, 4, 'grossspitz'),
(97, 'Kleinspitz', 'Miniature Spitz', 5, 4, 'kleinspitz'),
(97, 'Mittelspitz', 'Medium Spitz', 5, 4, 'mittelspitz'),
(261, 'Japanspitz', 'Japanese Spitz', 5, 5, 'japanspitz'),
(255, 'Akita', 'Akita', 5, 5, 'akita'),
(344, 'Amerikanischer Akita', 'American Akita', 5, 5, 'amerikanischer-akita'),
(257, 'Shiba', 'Shiba Inu', 5, 5, 'shiba'),
(270, 'Siberian Husky', 'Siberian Husky', 5, 1, 'siberian-husky'),
(243, 'Alaskan Malamute', 'Alaskan Malamute', 5, 1, 'alaskan-malamute'),
(212, 'Samojede', 'Samoyed', 5, 1, 'samojede'),
(291, 'Eurasier', 'Eurasier', 5, 5, 'eurasier'),
(205, 'Chow Chow', 'Chow Chow', 5, 5, 'chow-chow'),
(43, 'Basenji', 'Basenji', 5, 6, 'basenji'),
(289, 'Thai Ridgeback', 'Thai Ridgeback', 5, 7, 'thai-ridgeback'),
(94, 'Islandhund', 'Icelandic Sheepdog', 5, 3, 'islandhund'),

-- ═══ GRUPPE 6: Laufhunde, Schweißhunde ═══
(161, 'Beagle', 'Beagle', 6, 1, 'beagle'),
(163, 'Basset Hound', 'Basset Hound', 6, 1, 'basset-hound'),
(84, 'Bloodhound', 'Bloodhound', 6, 1, 'bloodhound'),
(153, 'Dalmatiner', 'Dalmatian', 6, 3, 'dalmatiner'),
(146, 'Rhodesian Ridgeback', 'Rhodesian Ridgeback', 6, 3, 'rhodesian-ridgeback'),
(217, 'Bayerischer Gebirgsschweißhund', 'Bavarian Mountain Hound', 6, 2, 'bayerischer-gebirgsschweisshund'),
(213, 'Hannoveraner Schweißhund', 'Hanover Hound', 6, 2, 'hannoveraner-schweisshund'),

-- ═══ GRUPPE 7: Vorstehhunde ═══
(119, 'Deutsch Kurzhaar', 'German Shorthaired Pointer', 7, 1, 'deutsch-kurzhaar'),
(98, 'Deutsch Drahthaar', 'German Wirehaired Pointer', 7, 1, 'deutsch-drahthaar'),
(117, 'Deutsch Langhaar', 'German Longhaired Pointer', 7, 1, 'deutsch-langhaar'),
(102, 'Kleiner Münsterländer', 'Small Munsterlander', 7, 1, 'kleiner-muensterlaender'),
(118, 'Grosser Münsterländer', 'Large Munsterlander', 7, 1, 'grosser-muensterlaender'),
(232, 'Weimaraner', 'Weimaraner', 7, 1, 'weimaraner'),
(57, 'Vizsla Kurzhaar', 'Hungarian Vizsla', 7, 1, 'vizsla'),
(239, 'Vizsla Drahthaar', 'Wirehaired Vizsla', 7, 1, 'vizsla-drahthaar'),
(234, 'Pudelpointer', 'Pudelpointer', 7, 1, 'pudelpointer'),
(2, 'English Setter', 'English Setter', 7, 2, 'english-setter'),
(6, 'Gordon Setter', 'Gordon Setter', 7, 2, 'gordon-setter'),
(120, 'Epagneul Breton', 'Brittany', 7, 1, 'epagneul-breton'),
(3, 'Irish Red Setter', 'Irish Red Setter', 7, 2, 'irish-red-setter'),

-- ═══ GRUPPE 8: Apportierhunde, Stöberhunde, Wasserhunde ═══
(111, 'Golden Retriever', 'Golden Retriever', 8, 1, 'golden-retriever'),
(122, 'Labrador Retriever', 'Labrador Retriever', 8, 1, 'labrador-retriever'),
(121, 'Flat Coated Retriever', 'Flat-Coated Retriever', 8, 1, 'flat-coated-retriever'),
(263, 'Chesapeake Bay Retriever', 'Chesapeake Bay Retriever', 8, 1, 'chesapeake-bay-retriever'),
(312, 'Nova Scotia Duck Tolling Retriever', 'Nova Scotia Duck Tolling Retriever', 8, 1, 'nova-scotia-duck-tolling-retriever'),
(110, 'Curly Coated Retriever', 'Curly-Coated Retriever', 8, 1, 'curly-coated-retriever'),
(5, 'Cocker Spaniel Englisch', 'English Cocker Spaniel', 8, 2, 'cocker-spaniel-englisch'),
(167, 'Amerikanischer Cocker Spaniel', 'American Cocker Spaniel', 8, 2, 'amerikanischer-cocker-spaniel'),
(125, 'English Springer Spaniel', 'English Springer Spaniel', 8, 2, 'english-springer-spaniel'),
(298, 'Lagotto Romagnolo', 'Lagotto Romagnolo', 8, 3, 'lagotto-romagnolo'),
(37, 'Portugiesischer Wasserhund', 'Portuguese Water Dog', 8, 3, 'portugiesischer-wasserhund'),
(336, 'Spanischer Wasserhund', 'Spanish Water Dog', 8, 3, 'spanischer-wasserhund'),

-- ═══ GRUPPE 9: Gesellschafts- und Begleithunde ═══
(172, 'Grosser Pudel', 'Standard Poodle', 9, 2, 'pudel-gross'),
(172, 'Zwergpudel', 'Miniature Poodle', 9, 2, 'zwergpudel'),
(172, 'Toypudel', 'Toy Poodle', 9, 2, 'toypudel'),
(215, 'Bichon Frisé', 'Bichon Frise', 9, 1, 'bichon-frise'),
(65, 'Malteser', 'Maltese', 9, 1, 'malteser'),
(250, 'Havaneser', 'Havanese', 9, 1, 'havaneser'),
(196, 'Bologneser', 'Bolognese', 9, 1, 'bologneser'),
(283, 'Coton de Tuléar', 'Coton de Tulear', 9, 1, 'coton-de-tulear'),
(233, 'Löwchen', 'Löwchen', 9, 1, 'loewchen'),
(227, 'Lhasa Apso', 'Lhasa Apso', 9, 5, 'lhasa-apso'),
(208, 'Shih Tzu', 'Shih Tzu', 9, 5, 'shih-tzu'),
(209, 'Tibet Terrier', 'Tibetan Terrier', 9, 5, 'tibet-terrier'),
(218, 'Chihuahua', 'Chihuahua', 9, 6, 'chihuahua'),
(136, 'Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel', 9, 7, 'cavalier-king-charles-spaniel'),
(253, 'Mops', 'Pug', 9, 11, 'mops'),
(101, 'Französische Bulldogge', 'French Bulldog', 9, 11, 'franzoesische-bulldogge'),
(77, 'Papillon', 'Papillon', 9, 9, 'papillon'),
(207, 'Pekinese', 'Pekingese', 9, 8, 'pekinese'),
(231, 'Tibet Spaniel', 'Tibetan Spaniel', 9, 5, 'tibet-spaniel'),
(206, 'Japanischer Chin', 'Japanese Chin', 9, 8, 'japanischer-chin'),
(192, 'Kromfohrländer', 'Kromfohrlander', 9, 10, 'kromfohrlaender'),
(352, 'Russischer Toy', 'Russian Toy', 9, 9, 'russischer-toy'),
(245, 'Boston Terrier', 'Boston Terrier', 9, 11, 'boston-terrier'),

-- ═══ GRUPPE 10: Windhunde ═══
(228, 'Afghanischer Windhund', 'Afghan Hound', 10, 1, 'afghanischer-windhund'),
(193, 'Barsoi', 'Borzoi', 10, 1, 'barsoi'),
(164, 'Deerhound', 'Scottish Deerhound', 10, 2, 'deerhound'),
(158, 'Greyhound', 'Greyhound', 10, 3, 'greyhound'),
(160, 'Irish Wolfhound', 'Irish Wolfhound', 10, 2, 'irish-wolfhound'),
(162, 'Whippet', 'Whippet', 10, 3, 'whippet'),
(200, 'Italienisches Windspiel', 'Italian Greyhound', 10, 3, 'italienisches-windspiel'),
(269, 'Saluki', 'Saluki', 10, 1, 'saluki'),
(307, 'Azawakh', 'Azawakh', 10, 3, 'azawakh'),
(285, 'Galgo Español', 'Spanish Greyhound', 10, 3, 'galgo-espanol')

ON CONFLICT (slug) DO NOTHING;
